### ISSUE TITLE
Encountered an error during conversion

### ISSUE THREAD

**Issue by amaralbc** [yeastrc/proxl-import-plink2#5]
Hello,

I'm getting an error when converting data from pLink 2.3.11 to xml to use on ProXL. If I run with -v as a flag for extra verbose, this is the output I'm getting:

pLink 2.x to proxl XML converter
Author: Michael Riffle <mriffle@uw.edu>
See: https://github.com/yeastrc/proxl-import-plink2
Version: 1.4.3

Loading search parameters... Done.
Loading search results... Done.
Writing proxl XML... java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
        at org.yeastrc.proxl_import.create_import_file_from_java_objects.main.CreateImportFileFromJavaObjectsMain.createImportFileFromJavaObjectsMain(CreateImportFileFromJavaObjectsMain.java:62)
        at org.yeastrc.proxl_import.create_import_file_from_java_objects.main.CreateImportFileFromJavaObjectsMain.createImportFileFromJavaObjectsMain(CreateImportFileFromJavaObjectsMain.java:43)
        at org.yeastrc.proxl.xml.plink2.builder.XMLBuilder.buildAndSaveXML(XMLBuilder.java:519)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.convertSearch(MainProgram.java:105)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.run(MainProgram.java:132)
        at picocli.CommandLine.execute(CommandLine.java:1160)
        at picocli.CommandLine.access$800(CommandLine.java:141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
        at picocli.CommandLine.run(CommandLine.java:1974)
        at picocli.CommandLine.run(CommandLine.java:1904)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.main(MainProgram.java:148)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 14 more

Encountered an error during conversion:
javax/xml/bind/JAXBContext

I've tried running from cmd on Windows 10 and also from Ubuntu after converting all the pLink file paths to be readable on Linux, same error on both.
Is there any setting I need to edit?

**Comment by danjasuw** [comment]
The executable jar needs to be updated to run on Java 9+.
It should work on Java 8.
I will let Michael Riffle know about this.

**Comment by danjasuw** [comment]
Added a new release 1.4.4 with the latest code that should run on Java 9+.

**Comment by amaralbc** [comment]
Excellent, the new release worked on first try.
Thank you!
